version: '3.9'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: npm run dev
    depends_on:
      - database

  frontend:
    build: ./client/moz-todo-react
    ports:
      - "3000:3000"
    volumes:
      - ./client/moz-todo-react:/app
    command: npm run dev
    depends_on:
      - backend

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: techhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
